name: purasiwa
description: "Shiva temple web app"
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  get_it: ^8.0.3
  slang: ^4.5.0
  slang_flutter: ^4.5.0
  sliver_tools: ^0.2.12
  google_fonts: ^6.2.1
  lucide_icons_flutter: ^1.2.9
  loading_indicator: ^3.1.1
  lottie: ^3.2.0
  flutter_svg: ^2.0.17
  cached_network_image: ^3.4.1
  go_router: ^14.8.1
  url_launcher: ^6.3.1
  url_launcher_web: ^2.4.0
  footer: ^0.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

slang:
  namespaces: true 
  output_directory: lib/i18n 
  output_file_name: translations.g.dart 