name: Deploy to Firebase Hosting on merge
on:
  push:
    branches:
      - main
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Install specific Flutter version
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.1'  # Set the specific version of Flutter

      # Run flutter build web
      - run: flutter build web

      # Deploy to Firebase Hosting
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_PURASIWA_98F91 }}
          channelId: live
          projectId: purasiwa-98f91
