name: Deploy to Firebase Hosting on PR
on: pull_request
permissions:
  checks: write
  contents: read
  pull-requests: write
jobs:
  build_and_preview:
    if: ${{ github.event.pull_request.head.repo.full_name == github.repository }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Install specific Flutter version
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.1'  # Set the specific version of Flutter

      # Run flutter build web
      - run: flutter build web

      # Deploy to Firebase Hosting for preview
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_PURASIWA_98F91 }}
          projectId: purasiwa-98f91
